export { default as Header } from './Header'
export { default as Dashboard } from './Dashboard'
export { default as Web3Name } from './Web3Name'
export { default as OurProject } from './OurProject'
export { default as HowToMint } from './HowToMint'