export { default as Header } from './Header'
export { default as Dashboard } from './Dashboard'
export { default as Web3Name } from './Web3Name'
export { default as OurProject } from './OurProject'
export { default as HowToMint } from './HowToMint'
export { default as Art } from './Art'
export { default as FAQ } from './FAQ'
export { default as Footer } from './Footer'